apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-executor
  template:
    metadata:
      labels:
        app: workflow-executor
    spec:
      serviceAccountName: default
      nodeSelector:
        kubernetes.io/hostname: etri-ser0001-cg0msb
      containers:
        - name: workflow-executor
          image: 192.168.0.56:5000/workflow-executor@sha256:fe5087a76f069573872e3b6be26564e93423a402079bf1d16c024a44d57a78df
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: PLACEMENT_ENGINE_URL
              value: http://placement-engine:8001
            - name: STATE_AGGREGATOR_URL
              value: http://state-aggregator:8000/workflow-event
            - name: EXECUTOR_NAMESPACE
              value: default
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-executor
spec:
  selector:
    app: workflow-executor
  ports:
    - name: http
      port: 8002
      targetPort: 8002
