apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: state-aggregator
  labels:
    app: state-aggregator
    release: prometheus
spec:
  selector:
    matchLabels:
      app: state-aggregator
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
