apiVersion: apps/v1
kind: Deployment
metadata:
  name: placement-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placement-engine
  template:
    metadata:
      labels:
        app: placement-engine
    spec:
      nodeSelector:
        kubernetes.io/hostname: etri-ser0001-cg0msb
      containers:
        - name: placement-engine
          image: 192.168.0.56:5000/placement-engine:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: STATE_AGGREGATOR_URL
              value: http://state-aggregator:8000
---
apiVersion: v1
kind: Service
metadata:
  name: placement-engine
spec:
  selector:
    app: placement-engine
  ports:
    - name: http
      port: 8001
      targetPort: 8001
